on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: pip install --user cpp-coveralls
    - name: Coveralls
      run: coveralls -r . -t ${{ secrets.coveralls }} --exclude test --exclude build --exclude concept --exclude blc
