name: cpplint

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ master, dev, test ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --recursive .