name: C/C++ CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ master, dev, test ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" .. -D test=true
    - name: build
      run: cd build && make
    - name: test
      run: cd build && ./test -s

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" .. -D test=true
    - name: build
      run: cd build && make
    - name: test
      run: cd build && ./test -s

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake .. -G "MinGW Makefiles" -D test=true -DCMAKE_SH="CMAKE_SH-NOTFOUND"
    - name: build
      run: cd build && mingw32-make
    - name: test
      run: cd build && test.exe -s