on: ["push", "pull_request"]

name: GCovr

jobs:

  build:
    name: Check Cover
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: install
      run: pip install gcovr
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" .. -D test=true
    - name: build
      run: cd build && make
    - name: test
      run: cd build && ./test
    - name: Coveralls
      run: gcovr -r .
